### ISSUE TITLE
week 7 is complete

### ISSUE THREAD

**Issue by hmkurth** [hmkurth/CommunityFoodResources#6]
@pawaitemadisoncollege week 7 is complete
See timelog and journal for reflections

**Comment by pawaitemadisoncollege** [comment]
@hmkurth It seems like you had to fight through a lot this week to get auth working! In hindsight, can you think of  troubleshooting or development approaches that might have helped you resolve any of the problems you solved sooner or faster?  

- [ ] As you add more functionality, remember to also restrict access to the controllers accessed by the jsps - a savvy user could go directly to the servlet and bypass your current security.

**Comment by hmkurth** [comment]
I'm not sure about development approaches, do you mean tdd?  I'll take any troubleshooting approach advice I can!  It's becoming difficult to know where to even start troubleshooting some of these problems...which logs to look at, where the traces can be found, etc.

**Comment by pawaitemadisoncollege** [comment]
I most often run into trouble when I write a lot of code or make several configuration changes, and then realize things are no longer working. Going back to see which of the many changes I made takes so much time, and it's at that point that I remember I need to do one small piece, make sure it didn't break anything, or that the change works, and then do the next thing.  Anyway, that's me, and thought maybe you'd discovered a similar approach for yourself.
