### ISSUE TITLE
checkpoint 3 ready

### ISSUE THREAD

**Issue by hmkurth** [hmkurth/CommunityFoodResources#7]
@pawaitemadisoncollege

**Comment by hmkurth** [comment]
you can log in as jcoyne supersecret1, i don't have new user setup yet.

**Comment by pawaitemadisoncollege** [comment]
Good morning @hmkurth! Is this the proper link to your deployed application? http://3.140.74.211:8080/Community%20Food%20Resources?? I'm not able to access it this morning and a not sure if the url is incorrect in the Indie project list in the student repo or if the ec2 instance needs a bounce?
<img width="1683" alt="Screen Shot 2021-03-24 at 8 48 03 AM" src="https://user-images.githubusercontent.com/13874466/112321109-a9a69780-8c7d-11eb-9737-65f69537f0e7.png">

**Comment by hmkurth** [comment]
I forgot to update the link after erasing the spaces, so it should be http://3.140.74.211:8080/CommunityFoodResources now

**Comment by pawaitemadisoncollege** [comment]
You hit CP3 @hmkurth! I think a lot of the really hard stuff is behind you now and this should give you a good base to start adding functionality!

Your site design is looking good - very nice attention to making this user-friendly in so many ways!

- [ ] I know you are still working to implement the api, but when you pick this up again, package names should be lower case: https://github.com/hmkurth/CommunityFoodResources/blob/3555adcc963e762c5e26dade2839fae6ba5e0b30/src/main/java/com/hmkurth/Api/AddressComponentsItem.java#L1


I'm going to poke around with that api a little bit to see if I can help move you forward there. More soon!
